import GitHubMark from '../brand/GitHubMark.jsx'
import {
  ArrowDownIcon,
  ArrowUpIcon,
  BatchIcon,
  BoltIcon,
  BranchIcon,
  CheckIcon,
  ClockIcon,
  CloneRepoIcon,
  CloseIcon,
  CommitHistoryIcon,
  CopyIcon,
  DashboardIcon,
  DeleteIcon,
  DiffIcon,
  EditIcon,
  ExternalLinkIcon,
  FolderIcon,
  ListLayoutIcon,
  MasonryLayoutIcon,
  MissingRepoWarningIcon,
  MonitorIcon,
  MoonIcon,
  MoreIcon,
  PauseIcon,
  PlayIcon,
  PlusIcon,
  RefreshSyncIcon,
  SearchIcon,
  SettingsIcon,
  SidebarPanelIcon,
  SunIcon,
  TerminalIcon,
  WarningIcon,
} from './CanonicalIcons.jsx'

export const APP_ICONS = Object.freeze({
  batch: BatchIcon,
  bolt: BoltIcon,
  dashboard: DashboardIcon,
  settings: SettingsIcon,
  sync: RefreshSyncIcon,
  folder: FolderIcon,
  branch: BranchIcon,
  github: GitHubMark,
  clock: ClockIcon,
  copy: CopyIcon,
  diff: DiffIcon,
  commitHistory: CommitHistoryIcon,
  search: SearchIcon,
  edit: EditIcon,
  pause: PauseIcon,
  play: PlayIcon,
  trash: DeleteIcon,
  warning: WarningIcon,
  warningMissingRepo: MissingRepoWarningIcon,
  sun: SunIcon,
  moon: MoonIcon,
  monitor: MonitorIcon,
  terminal: TerminalIcon,
  check: CheckIcon,
  close: CloseIcon,
  externalLink: ExternalLinkIcon,
  arrowDown: ArrowDownIcon,
  arrowUp: ArrowUpIcon,
  plus: PlusIcon,
  cloneRepo: CloneRepoIcon,
  listLayout: ListLayoutIcon,
  masonryLayout: MasonryLayoutIcon,
  sidebarPanel: SidebarPanelIcon,
  more: MoreIcon,
})
