import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const read = (relativePath) => readFileSync(join(here, relativePath), 'utf8')

test('mounts the review layer beside working changes before commit generation', () => {
  const main = read('../main.jsx')
  assert.match(main, /const AiReviewLayer = lazy\(\(\) => import\('\.\/ai\/AiReviewLayer\.jsx'\)\)/)
  assert.match(main, /import '\.\/ai\/AiReviewNavigation\.css'/)
  assert.match(main, /import '\.\/ai\/AiReviewStage4\.css'/)
  assert.doesNotMatch(main, /import '\.\/ai\/aiReviewNavigation\.js'/)
  const working = main.indexOf('<WorkingChangesLayer />')
  const review = main.indexOf('<AiReviewLayer />')
  const commit = main.indexOf('<AiCommitMessageLayer />')
  assert.ok(working >= 0 && working < review && review < commit)
})

test('review UI reuses a complete selected scope and refreshes only when completeness requires it', () => {
  const source = read('AiReviewLayer.jsx')
  assert.match(source, /function readToolbarSelectedCount\(root = document\)/)
  assert.match(source, /function shouldRefreshWorkingSummary\(scope, root = document\)/)
  assert.match(source, /selectedCount === null \|\| selectedCount === 0/)
  assert.match(source, /let nextScope = readWorkingReviewScope\(document\)/)
  assert.match(source, /if \(shouldRefreshWorkingSummary\(nextScope, document\)\)/)
  assert.match(source, /invoke\('get_repo_working_diff_summary', \{ repoPath: context\.repoPath \}\)/)
  assert.match(source, /cacheWorkingSummary\(context\.repoPath, latestSummary\)/)
  assert.match(source, /invoke\('preview_ai_review_scope'/)
  assert.match(source, /invoke\('run_ai_review'/)
  assert.match(source, /invoke\('cancel_ai_review_request'/)
  assert.match(source, /发送前确认 Review 范围/)
  assert.match(source, /开始 Review/)
  assert.match(source, /复制 Review/)
  assert.match(source, /重新运行/)
  assert.match(source, /结果已过期/)
  assert.match(source, /SEVERITIES = \['P0', 'P1', 'P2', 'P3'\]/)
})

test('review lifecycle suppresses stale requests when the working view closes', () => {
  const source = read('AiReviewLayer.jsx')
  assert.match(source, /if \(!mountNode \|\| !context\?\.repoPath\)/)
  assert.match(source, /invoke\('cancel_ai_review_request', \{ requestId \}\)/)
  assert.match(source, /activeRequestIdRef\.current = ''/)
  assert.match(source, /setRequest\(IDLE_REQUEST\)/)
  assert.match(source, /const requestCancellable = requestBusy && !NON_CANCELLABLE_PHASES\.has\(request\.phase\)/)
  assert.match(source, /if \(requestBusy && !requestCancellable\) return/)
})

test('completed Review results use the same batched fingerprint for live stale checks', () => {
  const source = read('AiReviewLayer.jsx')
  const status = read('../../src-tauri/src/ai/review_status.rs')
  const lib = read('../../src-tauri/src/lib.rs')
  assert.match(source, /REVIEW_STALE_CHECK_INTERVAL_MS = 2000/)
  assert.match(source, /invoke\('get_ai_review_scope_fingerprint'/)
  assert.match(source, /scopeKind: scope\.scopeKind/)
  assert.match(source, /currentFingerprint === fingerprint/)
  assert.match(source, /stale: true, currentSnapshotFingerprint/)
  assert.match(source, /window\.addEventListener\('focus', handleFocus\)/)
  assert.match(status, /pub async fn get_ai_review_scope_fingerprint/)
  assert.match(status, /capture_review_plan/)
  assert.match(lib, /ai::review_status::get_ai_review_scope_fingerprint/)
})

test('finding navigation clears file filters, preserves checkbox scope, and highlights a validated line', () => {
  const source = read('AiReviewLayer.jsx')
  const navigation = read('aiReviewNavigation.js')
  const workingView = read('../WorkingChangesView.jsx')
  const workingCell = read('../WorkingChangesFileCell.jsx')
  const workingScope = read('workingChangeScope.js')
  assert.match(source, /import \{ navigateReviewFinding \} from '\.\/aiReviewNavigation'/)
  assert.match(source, /onClick=\{\(\) => navigateReviewFinding\(finding\)\}/)
  assert.match(navigation, /setControlledInputValue\(search, ''\)/)
  assert.match(navigation, /const checkboxSnapshot = captureCheckboxState\(preview\)/)
  assert.match(navigation, /restoreCheckboxState\(checkboxSnapshot\)/)
  assert.match(navigation, /if \(checkbox\.checked !== checked\) checkbox\.click\(\)/)
  assert.match(navigation, /scrollToLine\(location\.line\)/)
  assert.match(navigation, /ai-review-line-target/)
  assert.match(workingCell, /data-file-path=\{filePath\}/)
  assert.match(navigation, /candidate\.getAttribute\('data-file-path'\) === path/)
  assert.match(navigation, /row\?\.querySelector\('\.working-changes-file-cell__preview'\)/)
  assert.match(workingScope, /path: asPath\(row\.getAttribute\('data-file-path'\)\)/)
  assert.match(workingScope, /fileId: asText\(checkbox\?\.getAttribute\('data-file-id'\)\)/)
  assert.doesNotMatch(navigation, /document\.addEventListener\('click'/)
  assert.doesNotMatch(workingView, /const \[batchMode, setBatchMode\]|batchModeRef|toggleBatchMode/)
  assert.match(workingView, /const \[selectedIds, setSelectedIds\] = useState\(\(\) => new Set\(\)\)/)
})

test('Review copying uses the existing Tauri clipboard boundary', () => {
  const source = read('AiReviewLayer.jsx')
  assert.match(source, /formatAiReviewForClipboard\(result\)/)
  assert.match(source, /invoke\('write_clipboard', \{ text \}\)/)
  assert.doesNotMatch(source, /navigator\.clipboard/)
})

test('backend keeps exact file scope while downgrading unverified model line locations', () => {
  const review = read('../../src-tauri/src/ai/review.rs')
  const commands = read('../../src-tauri/src/ai/review_commands.rs')
  const pipeline = read('../../src-tauri/src/ai/review_pipeline.rs')
  const batching = read('../../src-tauri/src/ai/batching.rs')
  const limits = read('../../src-tauri/src/ai/limits.rs')
  const schema = read('../../src-tauri/src/ai/schema.rs')
  const lib = read('../../src-tauri/src/lib.rs')
  assert.match(review, /REVIEW_PROMPT_VERSION: &str = "review-v1"/)
  assert.match(review, /P0\|P1\|P2\|P3/)
  assert.match(review, /allowed_paths\.contains\(path\)/)
  assert.match(review, /Review finding 引用了分析范围之外的文件/)
  assert.match(review, /build_allowed_line_map/)
  assert.match(review, /fn validate_lines\([\s\S]*\) -> \(Option<u32>, Option<u32>\)/)
  assert.match(review, /scoped_lines\.is_empty\(\)[\s\S]*return \(None, None\)/)
  assert.match(review, /downgrade to file-level navigation/)
  assert.doesNotMatch(review, /行号不在已分析的 Diff hunk 内/)
  assert.match(commands, /static REVIEW_PREVIEW_REGISTRY/)
  assert.match(commands, /MAX_PENDING_REVIEW_PREVIEWS/)
  assert.match(commands, /async fn store_preview_fingerprint/)
  assert.match(commands, /registry\.clear\(\)/)
  assert.match(commands, /capture_stable_review_plan/)
  assert.match(commands, /execute_review_plan/)
  assert.match(pipeline, /if first\.snapshots\.len\(\) <= 1/)
  assert.match(pipeline, /preview\.snapshot_fingerprint = self\.fingerprint\.clone\(\)/)
  assert.match(pipeline, /get_cached_review/)
  assert.match(pipeline, /put_cached_review/)
  assert.match(batching, /deterministic_target_batches/)
  assert.match(limits, /MAX_REVIEW_BATCH_FILES: usize = 8/)
  assert.match(schema, /pub struct AiReviewDelivery/)
  assert.match(schema, /pub struct AiReviewBatchFailure/)
  assert.match(lib, /ai::review_commands::preview_ai_review_scope/)
  assert.match(lib, /ai::review_commands::run_ai_review/)
})
