import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const readSource = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('mounts a dedicated branch reminder details layer after branch presentation', () => {
  const main = readSource('src/main.jsx')
  assert.match(main, /const BranchAttentionDetailLayer = lazy\(\(\) => import\('\.\/BranchAttentionDetailLayer\.jsx'\)\)/)
  assert.match(main, /import '\.\/BranchAttentionDetailActions\.css'/)
  const interaction = main.indexOf('<BranchManagementInteractionLayer />')
  const details = main.indexOf('<BranchAttentionDetailLayer />')
  const working = main.indexOf('<WorkingChangesLayer />')
  assert.ok(interaction >= 0 && interaction < details && details < working)
})

test('opens reminder details from the existing 查看详情 action without opening the generic branch hover', () => {
  const source = readSource('src/BranchAttentionDetailLayer.jsx')
  assert.match(source, /const ACTION_SELECTOR = '\.repo-card__branch-attention-action'/)
  assert.match(source, /document\.addEventListener\('click', handleActionClick, true\)/)
  assert.match(source, /event\.preventDefault\(\)/)
  assert.match(source, /event\.stopImmediatePropagation\?\.\(\)/)
  assert.match(source, /invoke\('get_repo_branch_overview'/)
  assert.match(source, /invoke\('get_repo_branch_management_meta'/)
  assert.match(source, /invoke\('get_repo_status'/)
  assert.match(source, /getBranchAttentionSummary\(dataState\.overview\)/)
  assert.match(source, /仅显示被计入仓库卡片提醒的其他分支/)
  assert.doesNotMatch(source, /mouseover|focusin|openMetaHoverCardByKey|branch-management-hover-expand/)
})

test('renders precise reminder reasons with focused resolution actions', () => {
  const source = readSource('src/BranchAttentionDetailLayer.jsx')
  const css = readSource('src/BranchAttentionDetailLayer.css')
  const actionCss = readSource('src/BranchAttentionDetailActions.css')
  assert.match(source, /buildAttentionEntries\(summary, dataState\.rows\)/)
  assert.match(source, /item\.kindLabel/)
  assert.match(source, /item\.reason/)
  assert.match(source, /label: '切换并跟踪'/)
  assert.match(source, /label: '同步'/)
  assert.match(source, /label: '重新绑定'/)
  assert.match(source, /label: '取消上游'/)
  assert.match(source, /invoke\(action\.command/)
  assert.match(source, /refresh_repo_git_metadata/)
  assert.match(source, /共 \$\{summary\.count\} 个其他分支/)
  assert.match(css, /\.branch-attention-detail__sheet/)
  assert.match(css, /\.branch-attention-detail__summary/)
  assert.match(css, /\.branch-attention-detail__row/)
  assert.match(css, /body\.branch-attention-detail-open/)
  assert.match(actionCss, /\.branch-attention-detail__primary-action/)
  assert.match(actionCss, /\.branch-attention-detail__copy-action/)
  assert.match(actionCss, /\.branch-attention-detail__feedback/)
})

test('uses shared branch and refresh icon authorities including icon-only sync', () => {
  const source = readSource('src/BranchAttentionDetailLayer.jsx')
  assert.match(source, /BranchIcon,[\s\S]*RefreshSyncIcon,[\s\S]*from '\.\/icons\/CanonicalIcons\.jsx'/)
  assert.doesNotMatch(source, /function BranchIcon\(/)
  assert.doesNotMatch(source, /function RefreshIcon\(/)
  assert.match(source, /syncAction = action\?\.command === 'sync_repo_branch'/)
  assert.match(source, /branch-attention-detail__primary-action--icon-only/)
  assert.match(source, /aria-label=\{syncAction \? `同步分支 \$\{displayName\}` : undefined\}/)
})

test('adds a protected per-row branch deletion flow', () => {
  const source = readSource('src/BranchAttentionDetailLayer.jsx')
  const deleteCss = readSource('src/BranchAttentionDetailDelete.css')
  assert.match(source, /import \{ readBranchForceDeleteDefault \} from '\.\/branchForceDeleteSettings\.js'/)
  assert.match(source, /buildBranchDeleteRequest/)
  assert.match(source, /DeleteIcon as CanonicalDeleteIcon/)
  assert.match(source, /className="branch-attention-detail__delete-action"/)
  assert.match(source, /disabled=\{rowBusy \|\| !row\?\.canDelete\}/)
  assert.match(source, /function DeleteConfirmDialog/)
  assert.match(source, /同时删除远端分支/)
  assert.match(source, /强制删除本地分支（git branch -D）/)
  assert.match(source, /const command = 'delete_repo_branches_batch'/)
  assert.doesNotMatch(source, /force_delete_repo_branches_batch/)
  assert.match(source, /requests: \[request\]/)
  assert.match(source, /await load\(context, \{ preserve: true \}\)/)
  assert.match(deleteCss, /\.branch-attention-detail__delete-action/)
  assert.match(deleteCss, /\.branch-attention-detail__delete-dialog/)
  assert.match(deleteCss, /\.branch-attention-detail__delete-confirm/)
})

test('keeps current, default and worktree branch deletion protections visible', () => {
  const source = readSource('src/BranchAttentionDetailLayer.jsx')
  assert.match(source, /Array\.isArray\(repoStatus\?\.modified\)/)
  assert.match(source, /Array\.isArray\(repoStatus\?\.conflicted\)/)
  assert.match(source, /当前工作区存在未提交改动或冲突/)
  assert.match(source, /disabled=\{rowBusy \|\| Boolean\(action\.disabledReason\)\}/)
  assert.match(source, /row\?\.deleteDisabledReason/)
  assert.match(source, /默认分支、当前分支和其他 worktree 中已检出的分支仍然受保护/)
})
